apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-backend
  labels:
    app: ticket-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-backend
  template:
    metadata:
      labels:
        app: ticket-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api
        # USE THE IMAGE WE BUILT (Not generic Golang)
        image: "gcr.io/my-company-sit-platform/ticket-backend:v1"
        imagePullPolicy: IfNotPresent
        
        # NO COMMAND/ARGS needed (The Dockerfile handles startup)
        
        ports:
        - containerPort: 8080
        
        env:
        - name: DB_HOST
          value: "10.231.0.3"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        
        # PROBE GOES HERE (Inside the container block)
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3

      # NO VOLUMES needed for code (It's baked into the image)