apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticket-backend-monitor
  namespace: monitoring
  labels:
    release: kube-stack
spec:
  selector:
    matchLabels:
      app: ticket-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /metrics
    interval: 15s