apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: ticket-backend
  template:
    metadata:
      labels:
        app: ticket-backend
    spec:
      containers:
      - name: ticket-backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          value: {{ .Values.backend.env.kafkaBroker }}
        - name: DB_HOST
          value: "10.231.0.3"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10