apiVersion: v1
kind: Service
metadata:
  name: ticket-backend
  labels:
    app: ticket-backend
spec:
  selector:
    app: ticket-backend
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: 8080