# Global settings
ingress:
  enabled: true
  # We use "gce" because that is the default Google Controller you are using
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"

# Backend Configuration
backend:
  replicaCount: 1
  image:
    repository: "gcr.io/my-company-sit-platform/ticket-backend"
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    type: NodePort       # <--- REQUIRED for GKE Ingress
    port: 80             # Service Port
    targetPort: 8080     # <--- FIXED: Matches your Go App's port
  env:
    kafkaBroker: "kafka-service:9092" 

# Frontend Configuration
frontend:
  replicaCount: 1
  image:
    repository: "gcr.io/my-company-sit-platform/ticket-frontend" # <--- FIXED: Was pointing to backend!
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    type: NodePort       # <--- REQUIRED for GKE Ingress
    port: 80             # Service Port
    targetPort: 80       # Matches Nginx Port